import pandas as pd

def sarima_explanation(game_name):
    description = ""
    if game_name == "Apex Legend":
        description = "The forecast charts for Apex Legends depict the game\’s peak player counts from late 2020 to mid-2026. The historical data (blue line) reveals periodic surges and drops in player numbers, which likely correspond to seasonal events or content updates. However, after mid-2023, there\’s a noticeable downward trend, showing a reduction in peak player counts. The green line, representing the SARIMA-based forecast, suggests that the player base is expected to stabilize around 200,000\–250,000 players over the next year, with some periodic fluctuations. The model\’s confidence interval (orange shaded area) grows wider over time, indicating greater uncertainty in long-term predictions. By mid-2026, this range spans from below zero to over 600,000 players — a sign that while the central forecast suggests a steady player base, real-world variability could lead to unexpected growth or decline. Despite the relatively high error metrics (RMSE and MAE), the forecast does not suggest any major surges or crashes, pointing instead to a plateauing trend in Apex Legends’ player numbers."
    elif game_name == "Baldur's Gate 3":
        description = "The historical data (blue line) shows a sharp spike in peak players around 2023—likely coinciding with the game’s launch or a major update—reaching a peak near 900,000 players. After this surge, the player base quickly dropped and has since stabilized at around 100,000–200,000 peak players. The SARIMA model (green line) forecasts a very slight decline in the player base throughout 2025–2026, indicating a stabilizing trend without significant growth or shrinkage. The orange confidence interval highlights moderate uncertainty in these predictions, although it suggests the game will maintain a steady core player base in the near future. With relatively lower RMSE and MAE (23,611 and 18,494), the model’s forecast seems reasonably reliable given the data’s volatility following the launch spike. Overall, the forecast suggests that while Baldur’s Gate 3’s peak player counts have dropped significantly from their post-launch highs, they are expected to settle into a consistent range around 100,000–200,000 players in the coming year."
    elif game_name == "CSGO":
        description = "The historical data (blue line) highlights a steady climb from nearly zero in 2012 to around 1.5 million peak players by mid-2025. Notably, there are periodic dips and peaks, likely corresponding to in-game updates, events, or seasonal effects, but the overall trend is strongly upward. The SARIMA model’s forecast (green line) predicts that this upward trend will continue into 2026, with peak player counts exceeding 2 million. The orange confidence interval grows wider over time, indicating that while the central forecast remains optimistic, the actual numbers could vary significantly—ranging from about 1.8 million to 2.5 million by 2026. Despite the relatively large RMSE (80,125) and MAE (68,220), the model suggests continued growth for CSGO’s player base. In short, the game’s popularity appears robust, with no signs of plateauing in the next year."
    elif game_name == "Cyberpunk 2077":
        description = "The forecast for Cyberpunk 2077 shows a game that peaked dramatically upon release in late 2020, reaching well over a million peak players. However, as the historical data shows, this was followed by a sharp and continuous decline in peak players through 2021 and into 2022, stabilizing below 100,000. Since then, it has experienced periodic small surges but has overall remained at low player counts. The SARIMA model's forecast (green line) suggests that Cyberpunk 2077's player base will remain relatively flat through 2026, with only minor fluctuations and no significant resurgence expected. The confidence interval (orange) widens slightly, indicating some uncertainty, but it generally supports a stable yet low player count trend. The game's massive initial hype has cooled, and while it maintains a small, consistent player base, the forecast doesn’t suggest any major rebound in popularity. The relatively low RMSE (47,607) and MAE (46,724) reflect this stable low-level activity, suggesting the model has a good fit for this game's current trend."
    elif game_name == "Destiny 2":
        description = "The forecast for Destiny 2 over the next year (green line) suggests a continuation of its historical pattern of fluctuating peak player counts. The historical data shows frequent spikes and dips, reflecting the game's cyclical player activity—likely tied to expansions, seasonal events, or major content updates. The SARIMA model forecast projects that Destiny 2 will hover around 50,000 to 100,000 peak players in the coming year, although the forecast’s confidence interval (orange) indicates significant uncertainty. The RMSE of around 47,000 and MAE of about 36,500 suggest a reasonable model fit, but the broad confidence interval underscores the game's inherent volatility. Overall, Destiny 2 is expected to maintain its oscillating player trend with no clear growth or decline, staying within the typical activity range observed in the historical data."
    elif game_name == "Dota 2":
        description = "The forecast for Dota 2 suggests a slight downward trend in peak player counts over the next year. The historical data shows a long-term growth period peaking around 2016-2017, followed by a gradual decline and then a more stable but slightly downward-sloping trend in recent years. The forecast (green line) indicates that peak player counts will continue to decline modestly, with a forecast range generally around 600,000 to 700,000 players. The confidence interval (orange) shows a fairly broad range, reflecting uncertainty in the game's cyclical player activity. The RMSE of about 130,000 and MAE of 119,000 are relatively high, indicating some volatility in the data. However, the model suggests that while Dota 2's peak player counts will likely decrease slightly, the game will remain stable at a high level of engagement over the coming year."
    elif game_name == "Elden Ring":
        description = "For Elden Ring, the forecast shows a sharp decline in peak player counts in the near term, likely driven by the game's lifecycle and waning post-launch excitement. The historical data show a strong launch spike in 2022, with a big decline followed by small player activity peaks — likely due to updates or DLCs. The forecast (green line) anticipates gradual stabilization at around 40,000–60,000 peak players by mid-2026, within a broad confidence interval (orange band) due to uncertainty in player behavior, especially if there are future expansions or marketing events. The RMSE and MAE are relatively low compared to the overall player counts, indicating a reasonably good fit. Despite the downward trend, the game still shows signs of a loyal, stable player base maintaining a steady player count over the next 12 months."
    elif game_name == "Monster Hunter World":
        description = "The forecast for Monster Hunter World suggests a gradual decline in peak players over the next year. Despite periodic spikes historically (likely due to expansions and events), the SARIMA model predicts that by mid-2026, the game's peak player count will be in the 30,000 to 40,000 range. The forecast’s confidence interval is fairly wide, indicating some uncertainty, but the model still shows a slight but consistent downward trend, likely because the game's big content updates have slowed down. The RMSE and MAE are low compared to the peak player counts, meaning the forecast has a good fit."
    elif game_name == "PUBG":
        description = "The PUBG forecast suggests a slight downward trend in peak player counts over the next year, stabilizing around the 500,000–700,000 range by mid-2026. Historically, PUBG peaked at over 3 million peak players in early 2018, and has been on a general decline since. The model shows a narrow confidence interval, which suggests that the SARIMA forecast is more confident in its predictions for PUBG compared to other games (like Monster Hunter World)."
    elif game_name == "Terraria":
        description = "The Terraria 12-month forecast suggests stable peak player numbers in the 60,000–70,000 range, with a slight downward trend. The confidence interval is tight, indicating good model confidence in the forecast. Historically, Terraria had significant peaks around 2015, 2020 (notably around the 1.4 update), but has since stabilized to a consistent player base."

    return description